name: Build sdist and upload to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build sdist and upload to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist
        run: |
          python -m build --sdist .
          ls -l dist
          tar tvfz dist/batoid_rubin-*.tar.gz

      # - name: Publish package to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.TEST_PYPI_TOKEN }}
      #     repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            password: ${{ secrets.PYPI_TOKEN }}
            verbose: true
